server:
  port:
    8082

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: mypassword

rabbitmq:
  exchange:
    name: user_exchange
  routing:
    key: user_routing_key